name: 'Telegram Message Action'
description: 'Send messages to a Telegram chat from GitHub Actions'
author: 'cbrgm'

inputs:
  token:
    description: 'Telegram authorization token'
    required: true
  to:
    description: 'Unique identifier for the target chat'
    required: true
  thread-id:
    description: "For supergroups. Thread identifier."
    required: false
  message:
    description: 'The message to send'
    required: false
  parse-mode:
    description: 'Mode for parsing entities in the message text'
    required: false
    default: 'markdown'
  disable-web-page-preview:
    description: 'Disables link previews for links in this message'
    required: false
    default: "false"
  disable-notification:
    description: 'Sends the message silently. Users will receive a notification with no sound'
    required: false
    default: "false"
  protect-content:
    description: 'Protects the contents of the sent message from forwarding and saving'
    required: false
    default: "false"
  dry-run:
    description: 'If set, do not send a real message but print the details instead'
    required: false
    default: "false"

runs:
  using: 'docker'
  image: 'docker://ghcr.io/cbrgm/telegram-github-action:v1'
  args:
    - --token
    - ${{ inputs.token }}
    - --message
    - ${{ inputs.message }}
    - --parse-mode
    - ${{ inputs.parse-mode }}
    - --to=${{ inputs.to }}
    - --thread-id=${{ inputs.thread-id }}
    - --disable-web-page-preview=${{ inputs.disable-web-page-preview }}
    - --disable-notification=${{ inputs.disable-notification }}
    - --protect-content=${{ inputs.protect-content }}
    - --dry-run=${{ inputs.dry-run }}

branding:
  icon: briefcase
  color: blue

