FROM arm32v6/alpine:3.20 AS build
RUN apk add --no-cache ca-certificates

FROM scratch

ENTRYPOINT ["/usr/bin/telegram-github-action"]

COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

COPY bin/telegram-github-action /usr/bin/telegram-github-action
